name: aura
description: 占卜与情感陪伴App（MVP版）
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # 状态管理
  provider: ^6.1.1
  # 路由管理
  go_router: ^12.1.3
  # 本地存储
  shared_preferences: ^2.2.2
  # 网络请求
  dio: ^5.4.0
  # 表单验证
  form_validator: ^2.1.1
  # 图片加载
  cached_network_image: ^3.3.0
  # 动画
  lottie: ^2.7.0
  # 权限管理
  permission_handler: ^11.1.0
  # 设备信息
  device_info_plus: ^9.1.1
  # 键盘监听
  flutter_keyboard_visibility: ^6.0.0
  # 日期时间选择器
  flutter_datetime_picker_plus: ^2.1.0
  # 国家选择器
  country_picker: ^2.0.25
  # 邮箱验证
  email_validator: ^2.1.17
  # 国际化相关
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/persona/
    - assets/images/taro/
    - assets/animations/
    - assets/geo/world_divisions.json
    

